### How to Import NumPy as np and Print the Version Number?

In [1]:
import numpy as np
print(np.__version__)

1.20.1


### Using Tuple to Create a NumPy Array

In [2]:
arrObj = np.array((23, 32, 65, 85))
arrObj

array([23, 32, 65, 85])

### Using List to Create a NumPy Array

In [3]:
arrObj = np.array([43, 23, 75, 15])
arrObj

array([43, 23, 75, 15])

### 0-D Arrays

In [4]:
arrObj = np.array(21)
arrObj

array(21)

### 1-D Arrays

In [6]:
arrObj = np.array([43, 23, 75, 15])
arrObj

array([43, 23, 75, 15])

### 2-D Arrays

In [8]:
arrObj = np.array([[12, 43, 21], [67, 32, 98]])
arrObj

array([[12, 43, 21],
       [67, 32, 98]])

### 3-D Arrays

In [9]:
arrObj = np.array([[[23, 45, 22], [45, 76, 23]], [[67, 23, 56], [12, 76, 63]]])
arrObj

array([[[23, 45, 22],
        [45, 76, 23]],

       [[67, 23, 56],
        [12, 76, 63]]])

### n-Dimensional Array

In [3]:
arrObj = np.array([23, 22, 65, 44], ndmin=5)
arrObj

array([[[[[23, 22, 65, 44]]]]])

### Find Dimensions of an Array

In [7]:
arrObj1 = np.array(21)
arrObj2 = np.array([43, 23, 75, 15])
arrObj3 = np.array([[12, 43, 21], [67, 32, 98]])
arrObj4 = np.array([[[23, 45, 22], [45, 76, 23]], [[67, 23, 56], [12, 76, 63]]])
print(arrObj1.ndim)
print(arrObj2.ndim)
print(arrObj3.ndim)
print(arrObj4.ndim)

0
1
2
3


### Access the Elements of the 1-D, 2-D, and 3-D Arrays

In [9]:
arrObj1 = np.array([43, 23, 75, 15])
arrObj2 = np.array([[12, 43, 21], [67, 32, 98]])
arrObj3 = np.array([[[23, 45, 22], [45, 76, 23]], [[67, 23, 56], [12, 76, 63]]])
print(arrObj1[2])
print(arrObj2[0, 2])
print(arrObj3[0, 1, 2])

75
21
23


### Check the Data Type of the NumPy Array Object

In [11]:
arrObj1 = np.array([1, 2, 3, 4])
arrObj2 = np.array([1.3, 6.8, 3.5, 9.2])
arrObj3 = np.array(['Welcome', 'to', 'MUO'])
print(arrObj1.dtype)
print(arrObj2.dtype)
print(arrObj3.dtype)

int32
float64
<U7


### Converting Integer Array to Float Array

In [3]:
arrObj = np.array([43, 23, 75, 15])
floatArr = arrObj.astype('f')
floatArr

array([43., 23., 75., 15.], dtype=float32)

### Converting Float Array to Integer Array

In [4]:
arrObj = np.array([1.3, 6.8, 3.5, 9.2])
intArr = arrObj.astype('i')
intArr

array([1, 6, 3, 9], dtype=int32)

### Copy a NumPy Array Into Another Array

In [6]:
oldArr = np.array([43, 23, 75, 15])
newArr = np.copy(oldArr)
newArr

array([43, 23, 75, 15])

### Find the Shape of an NumPy Array

In [7]:
arrObj = np.array([[12, 43, 21], [67, 32, 98]])
arrObj.shape

(2, 3)

### Reshape an Array

In [8]:
arrObj = np.array([43, 23, 75, 15, 34, 45])
reshapedArr = arrObj.reshape(2, 3)
reshapedArr

array([[43, 23, 75],
       [15, 34, 45]])

### Flatten an Array

In [10]:
arrObj = np.array([[12, 43, 21], [67, 32, 98]])
flattenedArr = arrObj.reshape(-1)
flattenedArr

array([12, 43, 21, 67, 32, 98])

### Sorting 1-D Array of Integers

In [2]:
arrObj = np.array([43, 23, 75, 15])
np.sort(arrObj)

array([15, 23, 43, 75])

### Sorting 1-D Array of Strings

In [3]:
arrObj = np.array(["Python", "JavaScript", "Solidity", "Golang"])
np.sort(arrObj)

array(['Golang', 'JavaScript', 'Python', 'Solidity'], dtype='<U10')

### Sorting 2-D Array of Integers

In [4]:
arrObj = np.array([[12, 43, 21], [67, 32, 98]])
np.sort(arrObj)

array([[12, 21, 43],
       [32, 67, 98]])